[project]
name = "taskanline-mcp"
description = "MCP-сервер TasKanLine"
requires-python = ">=3.13,<3.14"
dynamic = ["version"]
dependencies = ["taskanline-sdk",]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/taskanline_mcp/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/taskanline_mcp"]

[tool.uv.sources]
taskanline-sdk = { workspace = true }
